name: Docker Build and Push Frontend

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker Frontend
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: marcotechstarter/example-frontend
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push Docker image Frontend
        uses: docker/build-push-action@v5
        with:
          context: frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
