name: Docker Build and Push

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker auth
        id: meta1
        uses: docker/metadata-action@v5
        with:
          images: marcotechstarter/example-backend
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push Docker image Auth
        uses: docker/build-push-action@v5
        with:
          context: auth
          file: ./backend/Dockerfile
          push: true
          tags: ${{ steps.meta1.outputs.tags }}
          labels: ${{ steps.meta1.outputs.labels }}

      - name: Extract metadata (tags, labels) for Docker auth
        id: meta1
        uses: docker/metadata-action@v5
        with:
          images: marcotechstarter/example-frontend
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push Docker image Auth
        uses: docker/build-push-action@v5
        with:
          context: auth
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ steps.meta1.outputs.tags }}
          labels: ${{ steps.meta1.outputs.labels }}
